# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFyf72spvwPQbO6WpaQu-xtREd-kKxnK
"""

import numpy as np

A= np.array([[3, -0.1, -0.2],
            [oia 7, 0.31],
            [6:3, 8.2, 1811]])

b=np.array([7., 19,3, 71.43])

#intetalízactón
x= np.zeros_13ke(b) £ Vector de soluciones inicializado a cero
hiterstione = 10. 7 Minero de treraciones

tolerance = 18-5 % Toleroncia para La convergencia

y Método de Gauss-Setdel

prirt("Resultados de cada Steración:

for Steration ín range(n_iterations):
2ola = copy)

for 3 3n range(len(b)):
7 Suma de Los términos
siga = sum(als][3] * x13] for 3 in range(len(b)) 4£ 4
x3] = (6[8] - sigma) / ALEJE]

1 testrar Los resultados de La treración
print(F"Eteración [iteration + 1): 10")

7 Verificación de La convergencia.

3f mp.linalg.norm(x - X_ol, ord=mp.inf) < tolerance
print(f'Convengió en [iteration + 1) ¿teraciones.
break

7 Resultados finales
prine("Soluciones Finales